Add ability to get random word
lyndseybrowning/trie-prefix pull request #6
Opened 2018-05-22 03:10 UTC by fzembow

Implements #5 

Taking advantage of the trie structure to quickly get random words.

Also relaxed the constraint that prefixes be non zero-length strings. This way, `getWords` and `getPrefix` can reuse the same backing implementation.

2018-05-22 10:03 UTC, lyndseybrowning commented
This looks good but I'd like to review properly later :)

2018-05-22 15:42 UTC, lyndseybrowning requested changes
Please see comments attached.

2018-05-22 15:42 UTC, lyndseybrowning commented on src/recurseRandomWord.js
> +
Remove line break

2018-05-22 15:42 UTC, lyndseybrowning commented on src/recurseRandomWord.js
> +  if(branch === config.END_WORD) {
Add line break above if statement

2018-05-22 15:42 UTC, lyndseybrowning commented on src/index.js
> +      let prefixNode;
How about making prefixNode a ternary. I try to avoid using let wherever I can. Thoughts?

2018-06-19 10:02 UTC, lyndseybrowning commented
@fzembow Are you able to make the requested changes? I'm happy to make them if you are unable to do so as I'd like to get these changes merged in :)

2018-06-21 23:06 UTC, fzembow commented
@lyndseybrowning my apologies, in the intervening period I left my job and moved apartments so just getting back into things now :)

Addressed your changes, let me know if you see any other issues.

Cheers,
f

2018-07-06 06:22 UTC, lyndseybrowning approved these changes

2018-07-06 06:23 UTC, merged

2018-07-06 06:23 UTC, lyndseybrowning commented
Lovely, looks good. Thanks 👍